version: '3'
services:
    hornet:
        build:
            context: hornet/
            dockerfile: Dockerfile
        ports:
            - "15600:15600"
            - "14265:14265" 
            - "14626:14626"
            - "8081:8081"
            - "2222:222"
    node1:
        build:
            context: node/
            dockerfile: Dockerfile
            args:
                HORNETADDRESS: "hornet"
        ports:
            - "15601:15600"
            - "14266:14265" 
            - "14627:14626"
            - "8082:8081"
            - "2223:222"
            - "4001:4001"
        links:
            - "hornet:hornet"
    node2:
        build:
            context: node/
            dockerfile: Dockerfile
            args:
                HORNETADDRESS: "hornet"
        ports:
            - "15602:15600"
            - "14267:14265" 
            - "14628:14626"
            - "8083:8081"
            - "2224:222"
            - "4002:4001"
        links:
            - "hornet:hornet"
    node3:
        build:
            context: node/
            dockerfile: Dockerfile
            args:
                HORNETADDRESS: "hornet"
        ports:
            - "15603:15600"
            - "14268:14265" 
            - "14629:14626"
            - "8084:8081"
            - "2225:222"
            - "4003:4001"
        links:
            - "hornet:hornet"
    node4:
        build:
            context: node/
            dockerfile: Dockerfile
            args:
                HORNETADDRESS: "hornet"
        ports:
            - "15604:15600"
            - "14269:14265" 
            - "14630:14626"
            - "8085:8081"
            - "2226:222"
            - "4004:4001"
        links:
            - "hornet:hornet"
